### ISSUE TITLE
bug: 0.13 install failed macOS Sequoia 15.2 Apple M1 Pro

### ISSUE THREAD

**Issue by leeparayno** [eyaltoledano/claude-task-master#400]
### Description

Detailed description of the problem, including steps to reproduce the issue.

### Steps to Reproduce

1. Step-by-step instructions to reproduce the issue

I already had task-master-ai installed globally using the documented install command:

npm install -g task-master-ai

So, with this release I tried to install globally and got the errors in the attached picture. Output:

➜  ~ npm install -g task-master-ai
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'undici@7.8.0',
npm warn EBADENGINE   required: { node: '>=20.18.1' },
npm warn EBADENGINE   current: { node: 'v20.15.0', npm: '10.8.2' }
npm warn EBADENGINE }
npm warn deprecated node-domexception@1.0.0: Use your platform's native DOMException instead

changed 293 packages in 16s

67 packages are looking for funding
  run `npm fund` for details
➜  ~ npm list -g --depth=0
/Users/lee.parayno/.nvm/versions/node/v20.15.0/lib
├── @anthropic-ai/claude-code@0.2.35
├── @anthropic-ai/sdk@0.39.0
├── corepack@0.28.1
├── firebase-tools@13.33.0
├── npm@10.8.2
├── task-master-ai@0.13.0
├── typescript@5.8.3
└── windmill-cli@1.398.1

➜  ~ task-master
node:internal/modules/esm/resolve:854
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'boxen' imported from /Users/lee.parayno/.nvm/versions/node/v20.15.0/lib/node_modules/task-master-ai/scripts/modules/ui.js
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

### Expected Behavior

I expected the install to be clean and I would be able to use the "task-master" globally.

### Actual Behavior

Describe clearly what the actual outcome or behavior is.

### Screenshots or Logs

Provide screenshots, logs, or error messages if applicable.

### Environment

- Task Master version:
- Node.js version:
- Operating system:
- IDE (if applicable):

### Additional Context

Any additional information or context that might help diagnose the issue.

**Comment by FTAnalytics** [comment]
Same issue here. I then installed boxen, next issue was client table3, installed that. Now I get a Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/opt/homebrew/lib/node_modules/task-master-ai/src/ai-providers/anthropic.js'

**Comment by ComputerPers** [comment]
Same here
```
(.venv) pc:folder username$ npx -y --package=task-master-ai task-master-ai
node:internal/modules/package_json_reader:267
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'boxen' imported from /Users/username,/.npm/_npx/0726791833487271/node_modules/task-master-ai/scripts/modules/task-manager/analyze-task-complexity.js
    at Object.getPackageJSONURL (node:internal/modules/package_json_reader:267:9)
    at packageResolve (node:internal/modules/esm/resolve:768:81)
    at moduleResolve (node:internal/modules/esm/resolve:854:18)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:780:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:704:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:687:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:305:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:137:49) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v23.11.0
```

**Comment by AshesOfPhoenix** [comment]
I have the same issue too

Running on WSL: Ubuntu 22.04.5 LTS

`node:internal/modules/esm/resolve:275
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/ashesofphoenix/.nvm/versions/node/v23.11.0/lib/node_modules/task-master-ai/src/ai-providers/anthropic.js' imported from /home/ashesofphoenix/.nvm/versions/node/v23.11.0/lib/node_modules/task-master-ai/scripts/modules/ai-services-unified.js
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:780:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:704:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:687:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:305:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:137:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///home/ashesofphoenix/.nvm/versions/node/v23.11.0/lib/node_modules/task-master-ai/src/ai-providers/anthropic.js'
}

Node.js v23.11.0
`

**Comment by bitflorist** [comment]
+1 cannot run it
 - OSX Sequoia 

I also have problem to get it working without global installation. 

Fallback to 0.12.1, but it is necessary to adjust the command again:

{
  "mcpServers": {
    "taskmaster-ai": {
      "command": "npx",
      "args": ["-y", "task-master-ai"],
      "env": {
        "ANTHROPIC_API_KEY": "xxxxxxxxx",
        "PERPLEXITY_API_KEY": "xxxxxxxxx"
      }
    }
  }
}

**Comment by DavidSchargel** [comment]
With v0.13.1 on MacOS Sequoia:

```
node:internal/modules/esm/resolve:275
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/david/.asdf/installs/nodejs/23.11.0/lib/node_modules/task-master-ai/src/ai-providers/anthropic.js' imported from /Users/david/.asdf/installs/nodejs/23.11.0/lib/node_modules/task-master-ai/scripts/modules/ai-services-unified.js
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:780:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:704:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:687:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:305:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:137:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/david/.asdf/installs/nodejs/23.11.0/lib/node_modules/task-master-ai/src/ai-providers/anthropic.js'
}

Node.js v23.11.0
```

**Comment by DavidSchargel** [comment]
Fixed and working with v0.13.1.

**Comment by Crunchyman-ralph** [comment]
Yup, resolved in 0.13.2
